name: flutter_paypalredesign
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/chip_thumb.png
    - assets/images/icon_home.png
    - assets/images/icon_orion_user-group.png
    - assets/images/icon_recieve.png
    - assets/images/icon_school-bell.png
    - assets/images/icon_send.png
    - assets/images/icon_settings.png
    - assets/images/icon_shop.png
    - assets/images/Nike.png
    - assets/images/Paypal-logo-header.png
    - assets/images/Paypal-logo.png
    - assets/images/photo.png
    - assets/images/Visa-logo.png

  fonts:
    - family: sfprotext
      fonts:
        - asset: assets/fonts/sfprotext/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/sfprotext/SF-Pro-Text-Semibold.otf
        - asset: assets/fonts/sfprotext/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/sfprotext/SF-Pro-Text-Bold.otf
    - family: sfprotext
      fonts:
        - asset: assets/fonts/vistolsanslight/VistolSans-Light.otf
